### ISSUE TITLE
Amazon s3

### ISSUE THREAD

**Issue by SolomonBier** [abiaad/PAAImageView#11]
Great stuff ! 

Does this include AFNetworkings AFAmazonS3Manager? Can we use this to download from s3?

**Comment by abiaad** [comment]
Thx !

By S3 you mean with API key etc ... ? At this time I don't think so. But you can for it and improve it ;)

**Comment by SolomonBier** [comment]
Great, will do !

**Comment by SolomonBier** [comment]
Closing as I forked and added necessary features :)
