### ISSUE TITLE
Can't install via cocoapods

### ISSUE THREAD

**Issue by malcommac** [abiaad/PAAImageView#13]
It returns:
[!] Unable to find a specification for `PAAImageView`

**Comment by Spacelapp** [comment]
Same here...

**Comment by abiaad** [comment]
I created a pull request for podspec file. If you can't wait you can simply write :

```pod 'PAAImageView', :git => "https://github.com/abiaad/PAAImageView.git"```

**Comment by abiaad** [comment]
Problem solved. Thx
