### ISSUE TITLE
completion handler

### ISSUE THREAD

**Issue by malcommac** [abiaad/PAAImageView#14]
A completion handler with success/error of the operation inside setImageURL method could be useful in order to place another (local) image if download fails or url is not valid.
It should be very easy to integrate if you have used AFNetworking.
Great class man!

**Comment by abiaad** [comment]
Thanks !
So a placeholder image for unsuccessful download. Is that your point ?

**Comment by abiaad** [comment]
Done and tagged 1.1.0. Thx !
